export default [
	{
		link: "https://cars-app-ui.vercel.app/pl/fleet-list",
		img: "/port6.png",
		buttonText: "Live",
		title: "ElitesCars",
		description:
			"A responsive web application for managing and browsing car fleets. During my internship at CodeWords, I developed the landing page, implemented multi-language support with i18next, integrated Stripe for payments, added a feature to initiate conversations with listing owners, and implemented pagination through MongoDB database integration.",
		tools: [
			"React",
			"Next.js",
			"NestJS",
			"MongoDB",
			"JavaScript",
			"TypeScript",
			"Tailwind CSS",
			"SCSS",
			"Stripe",
			"i18next",
			"NextAuth",
			"Bootstrap",
			"Shadcn",
		],
	},
	{
		link: "https://ai-interview-recruiter.vercel.app/",
		img: "/port4.png",
		buttonText: "Live",
		title: "AI Interview Recruiter",
		description:
			"AI Interview Recruiter is an advanced and responsive web application designed for coaching users on interview preparation. It employs state-of-the-art technology to generate tailored interview questions based on user data such as job title, job description, and professional experience. Users can record their answers, which are converted to text using speech-to-text technology, and analyzed by AI to provide feedback and ratings.",
		tools: [
			"React",
			"Next.js",
			"PostgreSQL",
			"JavaScript",
			"Tailwind CSS",
			"Google Gemini",
			"RESTful API",
			"Drizzle",
			"Clerk",
			"Shadcn",
			"Stripe",
		],
	},
	{
		link: "https://github.com/patrykswiderski/simple-meditation",
		img: "/port7.png",
		buttonText: "Check code",
		title: "Meditation App",
		description:
			"A mobile application built with React Native and Expo Go, allowing users to choose from default audio files or select their own from the phone’s library. The app enables users to set the duration of meditation sessions and select affirmations, with multi-language support for an enhanced personalized experience.",
		tools: ["React Native", "TypeScript", "Expo Go", "Tailwind CSS"],
	},
	{
		link: "https://online-grocery-store-app.vercel.app/",
		img: "/port1.png",
		buttonText: "Live",
		title: "Online Grocery Shop",
		description:
			"Online Grocery Store, designed to streamline your grocery shopping experience through advanced technology and user-friendly interfaces. Platform offers a seamless, efficient, and secure way to shop for groceries from the comfort of your home.",
		tools: [
			"React",
			"Next.js",
			"PostgreSQL",
			"JavaScript",
			"Tailwind CSS",
			"RESTful API",
			"PayPal Payments",
			"Shadcn",
		],
	},
	{
		link: "https://movieflix-app-seven.vercel.app/",
		img: "/port3.png",
		buttonText: "Live",
		title: "Movieflix",
		description:
			"MovieFlix is a modern single page and responsive web application designed to provide users with an immersive movie browsing experience. The platform allows users to explore, search, and get detailed information about a vast collection of movies, TV series.",
		tools: [
			"React",
			"Next.js",
			"Redux",
			"JavaScript",
			"Tailwind CSS",
			"RESTful API",
			"Axios",
			"Accessibility (a11y)",
			"SQL",
		],
	},
	{
		link: "https://patrykswiderski.github.io/perfume-shop-project/",
		img: "/port2.png",
		title: "Perfume Online Shop",
		description:
			"E-commerce responsive application for a perfume shop using HTML, CSS, SASS, JavaScript. Included features like product display, detailed views, user reviews, and a checkout process.",
		tools: ["React", "HTML", "CSS", "SCSS", "Gulp", "JavaScript", "BEM"],
	},
];
